//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 09:57:18 AM CET 
//


package cz.honzakasik.upol.where2study.datamanage.jaxbmodels.rozvrhbymistnostresponse;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.honzakasik.upol.where2study.restclients.jaxbmodels.rozvrhbymistnostresponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Datum_QNAME = new QName("", "datum");
    private final static QName _RoakIdno_QNAME = new QName("", "roakIdno");
    private final static QName _ReferencedIdno_QNAME = new QName("", "referencedIdno");
    private final static QName _HodinaDo_QNAME = new QName("", "hodinaDo");
    private final static QName _Kontakt_QNAME = new QName("", "kontakt");
    private final static QName _Prijmeni_QNAME = new QName("", "prijmeni");
    private final static QName _Jmeno_QNAME = new QName("", "jmeno");
    private final static QName _VsichniUciteleUcitIdno_QNAME = new QName("", "vsichniUciteleUcitIdno");
    private final static QName _PlanObsazeni_QNAME = new QName("", "planObsazeni");
    private final static QName _Den_QNAME = new QName("", "den");
    private final static QName _Rok_QNAME = new QName("", "rok");
    private final static QName _HodinaSkutDo_QNAME = new QName("", "hodinaSkutDo");
    private final static QName _Platnost_QNAME = new QName("", "platnost");
    private final static QName _UcitIdno_QNAME = new QName("", "ucitIdno");
    private final static QName _Budova_QNAME = new QName("", "budova");
    private final static QName _DatumDo_QNAME = new QName("", "datumDo");
    private final static QName _Obsazeni_QNAME = new QName("", "obsazeni");
    private final static QName _TitulPred_QNAME = new QName("", "titulPred");
    private final static QName _TydenZkr_QNAME = new QName("", "tydenZkr");
    private final static QName _CasovaRada_QNAME = new QName("", "casovaRada");
    private final static QName _VsichniUciteleJmenaTituly_QNAME = new QName("", "vsichniUciteleJmenaTituly");
    private final static QName _HodinaOd_QNAME = new QName("", "hodinaOd");
    private final static QName _HodinaSkutOd_QNAME = new QName("", "hodinaSkutOd");
    private final static QName _Predmet_QNAME = new QName("", "predmet");
    private final static QName _TydenOd_QNAME = new QName("", "tydenOd");
    private final static QName _Owner_QNAME = new QName("", "owner");
    private final static QName _TypAkce_QNAME = new QName("", "typAkce");
    private final static QName _Nazev_QNAME = new QName("", "nazev");
    private final static QName _TitulZa_QNAME = new QName("", "titulZa");
    private final static QName _DatumOd_QNAME = new QName("", "datumOd");
    private final static QName _KapacitaMistnosti_QNAME = new QName("", "kapacitaMistnosti");
    private final static QName _TydenDo_QNAME = new QName("", "tydenDo");
    private final static QName _VsichniUcitelePrijmeni_QNAME = new QName("", "vsichniUcitelePrijmeni");
    private final static QName _Semestr_QNAME = new QName("", "semestr");
    private final static QName _DenZkr_QNAME = new QName("", "denZkr");
    private final static QName _Tyden_QNAME = new QName("", "tyden");
    private final static QName _DruhAkce_QNAME = new QName("", "druhAkce");
    private final static QName _TypAkceZkr_QNAME = new QName("", "typAkceZkr");
    private final static QName _Zamestnanec_QNAME = new QName("", "zamestnanec");
    private final static QName _Mistnost_QNAME = new QName("", "mistnost");
    private final static QName _Katedra_QNAME = new QName("", "katedra");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.honzakasik.upol.where2study.restclients.jaxbmodels.rozvrhbymistnostresponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RozvrhovaAkce }
     * 
     */
    public RozvrhovaAkce createRozvrhovaAkce() {
        return new RozvrhovaAkce();
    }

    /**
     * Create an instance of {@link Ucitel }
     * 
     */
    public Ucitel createUcitel() {
        return new Ucitel();
    }

    /**
     * Create an instance of {@link Rozvrh }
     * 
     */
    public Rozvrh createRozvrh() {
        return new Rozvrh();
    }

    /**
     * Create an instance of {@link GetRozvrhByMistnostResponse }
     * 
     */
    public GetRozvrhByMistnostResponse createGetRozvrhByMistnostResponse() {
        return new GetRozvrhByMistnostResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDatum(String value) {
        return new JAXBElement<String>(_Datum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "roakIdno")
    public JAXBElement<BigInteger> createRoakIdno(BigInteger value) {
        return new JAXBElement<BigInteger>(_RoakIdno_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "referencedIdno")
    public JAXBElement<BigInteger> createReferencedIdno(BigInteger value) {
        return new JAXBElement<BigInteger>(_ReferencedIdno_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hodinaDo")
    public JAXBElement<BigInteger> createHodinaDo(BigInteger value) {
        return new JAXBElement<BigInteger>(_HodinaDo_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kontakt")
    public JAXBElement<String> createKontakt(String value) {
        return new JAXBElement<String>(_Kontakt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "prijmeni")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrijmeni(String value) {
        return new JAXBElement<String>(_Prijmeni_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jmeno")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createJmeno(String value) {
        return new JAXBElement<String>(_Jmeno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vsichniUciteleUcitIdno")
    public JAXBElement<String> createVsichniUciteleUcitIdno(String value) {
        return new JAXBElement<String>(_VsichniUciteleUcitIdno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "planObsazeni")
    public JAXBElement<BigInteger> createPlanObsazeni(BigInteger value) {
        return new JAXBElement<BigInteger>(_PlanObsazeni_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "den")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDen(String value) {
        return new JAXBElement<String>(_Den_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rok")
    public JAXBElement<BigInteger> createRok(BigInteger value) {
        return new JAXBElement<BigInteger>(_Rok_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hodinaSkutDo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createHodinaSkutDo(String value) {
        return new JAXBElement<String>(_HodinaSkutDo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "platnost")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPlatnost(String value) {
        return new JAXBElement<String>(_Platnost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ucitIdno")
    public JAXBElement<BigInteger> createUcitIdno(BigInteger value) {
        return new JAXBElement<BigInteger>(_UcitIdno_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "budova")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBudova(String value) {
        return new JAXBElement<String>(_Budova_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datumDo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDatumDo(String value) {
        return new JAXBElement<String>(_DatumDo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "obsazeni")
    public JAXBElement<BigInteger> createObsazeni(BigInteger value) {
        return new JAXBElement<BigInteger>(_Obsazeni_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "titulPred")
    public JAXBElement<String> createTitulPred(String value) {
        return new JAXBElement<String>(_TitulPred_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tydenZkr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTydenZkr(String value) {
        return new JAXBElement<String>(_TydenZkr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "casovaRada")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCasovaRada(String value) {
        return new JAXBElement<String>(_CasovaRada_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vsichniUciteleJmenaTituly")
    public JAXBElement<String> createVsichniUciteleJmenaTituly(String value) {
        return new JAXBElement<String>(_VsichniUciteleJmenaTituly_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hodinaOd")
    public JAXBElement<BigInteger> createHodinaOd(BigInteger value) {
        return new JAXBElement<BigInteger>(_HodinaOd_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hodinaSkutOd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createHodinaSkutOd(String value) {
        return new JAXBElement<String>(_HodinaSkutOd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "predmet")
    public JAXBElement<String> createPredmet(String value) {
        return new JAXBElement<String>(_Predmet_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tydenOd")
    public JAXBElement<BigInteger> createTydenOd(BigInteger value) {
        return new JAXBElement<BigInteger>(_TydenOd_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "owner")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOwner(String value) {
        return new JAXBElement<String>(_Owner_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "typAkce")
    public JAXBElement<String> createTypAkce(String value) {
        return new JAXBElement<String>(_TypAkce_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nazev")
    public JAXBElement<String> createNazev(String value) {
        return new JAXBElement<String>(_Nazev_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "titulZa")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTitulZa(String value) {
        return new JAXBElement<String>(_TitulZa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datumOd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDatumOd(String value) {
        return new JAXBElement<String>(_DatumOd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kapacitaMistnosti")
    public JAXBElement<BigInteger> createKapacitaMistnosti(BigInteger value) {
        return new JAXBElement<BigInteger>(_KapacitaMistnosti_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tydenDo")
    public JAXBElement<BigInteger> createTydenDo(BigInteger value) {
        return new JAXBElement<BigInteger>(_TydenDo_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vsichniUcitelePrijmeni")
    public JAXBElement<String> createVsichniUcitelePrijmeni(String value) {
        return new JAXBElement<String>(_VsichniUcitelePrijmeni_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "semestr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSemestr(String value) {
        return new JAXBElement<String>(_Semestr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "denZkr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDenZkr(String value) {
        return new JAXBElement<String>(_DenZkr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tyden")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTyden(String value) {
        return new JAXBElement<String>(_Tyden_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "druhAkce")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDruhAkce(String value) {
        return new JAXBElement<String>(_DruhAkce_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "typAkceZkr")
    public JAXBElement<String> createTypAkceZkr(String value) {
        return new JAXBElement<String>(_TypAkceZkr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zamestnanec")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createZamestnanec(String value) {
        return new JAXBElement<String>(_Zamestnanec_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mistnost")
    public JAXBElement<BigInteger> createMistnost(BigInteger value) {
        return new JAXBElement<BigInteger>(_Mistnost_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "katedra")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createKatedra(String value) {
        return new JAXBElement<String>(_Katedra_QNAME, String.class, null, value);
    }

}
