//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 09:57:18 AM CET 
//


package cz.honzakasik.upol.where2study.datamanage.jaxbmodels.rozvrhbymistnostresponse;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}roakIdno" minOccurs="0"/>
 *         &lt;element ref="{}nazev"/>
 *         &lt;element ref="{}katedra" minOccurs="0"/>
 *         &lt;element ref="{}predmet"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}ucitIdno"/>
 *           &lt;element ref="{}ucitel"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}rok"/>
 *         &lt;element ref="{}budova"/>
 *         &lt;element ref="{}mistnost"/>
 *         &lt;element ref="{}kapacitaMistnosti"/>
 *         &lt;element ref="{}planObsazeni" minOccurs="0"/>
 *         &lt;element ref="{}obsazeni" minOccurs="0"/>
 *         &lt;element ref="{}typAkce"/>
 *         &lt;element ref="{}typAkceZkr"/>
 *         &lt;element ref="{}semestr" minOccurs="0"/>
 *         &lt;element ref="{}platnost"/>
 *         &lt;element ref="{}den"/>
 *         &lt;element ref="{}denZkr"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}hodinaOd"/>
 *           &lt;element ref="{}hodinaDo"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}hodinaSkutOd"/>
 *         &lt;element ref="{}hodinaSkutDo"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}tydenOd"/>
 *           &lt;element ref="{}tydenDo"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}tyden"/>
 *         &lt;element ref="{}tydenZkr"/>
 *         &lt;element ref="{}casovaRada" minOccurs="0"/>
 *         &lt;element ref="{}kontakt" minOccurs="0"/>
 *         &lt;element ref="{}datum" minOccurs="0"/>
 *         &lt;element ref="{}datumOd"/>
 *         &lt;element ref="{}datumDo"/>
 *         &lt;element ref="{}druhAkce"/>
 *         &lt;element ref="{}vsichniUciteleUcitIdno"/>
 *         &lt;element ref="{}vsichniUciteleJmenaTituly"/>
 *         &lt;element ref="{}vsichniUcitelePrijmeni"/>
 *         &lt;element ref="{}referencedIdno"/>
 *         &lt;element ref="{}owner"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roakIdno",
    "nazev",
    "katedra",
    "predmet",
    "ucitIdno",
    "ucitel",
    "rok",
    "budova",
    "mistnost",
    "kapacitaMistnosti",
    "planObsazeni",
    "obsazeni",
    "typAkce",
    "typAkceZkr",
    "semestr",
    "platnost",
    "den",
    "denZkr",
    "hodinaOd",
    "hodinaDo",
    "hodinaSkutOd",
    "hodinaSkutDo",
    "tydenOd",
    "tydenDo",
    "tyden",
    "tydenZkr",
    "casovaRada",
    "kontakt",
    "datum",
    "datumOd",
    "datumDo",
    "druhAkce",
    "vsichniUciteleUcitIdno",
    "vsichniUciteleJmenaTituly",
    "vsichniUcitelePrijmeni",
    "referencedIdno",
    "owner"
})
@XmlRootElement(name = "rozvrhovaAkce")
public class RozvrhovaAkce {

    protected BigInteger roakIdno;
    @XmlElement(required = true)
    protected String nazev;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String katedra;
    @XmlElement(required = true)
    protected String predmet;
    protected BigInteger ucitIdno;
    protected Ucitel ucitel;
    @XmlElement(required = true)
    protected BigInteger rok;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String budova;
    @XmlElement(required = true)
    protected BigInteger mistnost;
    @XmlElement(required = true)
    protected BigInteger kapacitaMistnosti;
    protected BigInteger planObsazeni;
    protected BigInteger obsazeni;
    @XmlElement(required = true)
    protected String typAkce;
    @XmlElement(required = true)
    protected String typAkceZkr;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String semestr;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String platnost;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String den;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String denZkr;
    protected BigInteger hodinaOd;
    protected BigInteger hodinaDo;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String hodinaSkutOd;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String hodinaSkutDo;
    protected BigInteger tydenOd;
    protected BigInteger tydenDo;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tyden;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tydenZkr;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String casovaRada;
    protected String kontakt;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String datum;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String datumOd;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String datumDo;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String druhAkce;
    @XmlElement(required = true)
    protected String vsichniUciteleUcitIdno;
    @XmlElement(required = true)
    protected String vsichniUciteleJmenaTituly;
    @XmlElement(required = true)
    protected String vsichniUcitelePrijmeni;
    @XmlElement(required = true)
    protected BigInteger referencedIdno;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String owner;

    /**
     * Gets the value of the roakIdno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRoakIdno() {
        return roakIdno;
    }

    /**
     * Sets the value of the roakIdno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRoakIdno(BigInteger value) {
        this.roakIdno = value;
    }

    /**
     * Gets the value of the nazev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazev() {
        return nazev;
    }

    /**
     * Sets the value of the nazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazev(String value) {
        this.nazev = value;
    }

    /**
     * Gets the value of the katedra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKatedra() {
        return katedra;
    }

    /**
     * Sets the value of the katedra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKatedra(String value) {
        this.katedra = value;
    }

    /**
     * Gets the value of the predmet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredmet() {
        return predmet;
    }

    /**
     * Sets the value of the predmet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredmet(String value) {
        this.predmet = value;
    }

    /**
     * Gets the value of the ucitIdno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUcitIdno() {
        return ucitIdno;
    }

    /**
     * Sets the value of the ucitIdno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUcitIdno(BigInteger value) {
        this.ucitIdno = value;
    }

    /**
     * Gets the value of the ucitel property.
     * 
     * @return
     *     possible object is
     *     {@link Ucitel }
     *     
     */
    public Ucitel getUcitel() {
        return ucitel;
    }

    /**
     * Sets the value of the ucitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ucitel }
     *     
     */
    public void setUcitel(Ucitel value) {
        this.ucitel = value;
    }

    /**
     * Gets the value of the rok property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRok() {
        return rok;
    }

    /**
     * Sets the value of the rok property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRok(BigInteger value) {
        this.rok = value;
    }

    /**
     * Gets the value of the budova property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBudova() {
        return budova;
    }

    /**
     * Sets the value of the budova property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBudova(String value) {
        this.budova = value;
    }

    /**
     * Gets the value of the mistnost property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMistnost() {
        return mistnost;
    }

    /**
     * Sets the value of the mistnost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMistnost(BigInteger value) {
        this.mistnost = value;
    }

    /**
     * Gets the value of the kapacitaMistnosti property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKapacitaMistnosti() {
        return kapacitaMistnosti;
    }

    /**
     * Sets the value of the kapacitaMistnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKapacitaMistnosti(BigInteger value) {
        this.kapacitaMistnosti = value;
    }

    /**
     * Gets the value of the planObsazeni property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlanObsazeni() {
        return planObsazeni;
    }

    /**
     * Sets the value of the planObsazeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlanObsazeni(BigInteger value) {
        this.planObsazeni = value;
    }

    /**
     * Gets the value of the obsazeni property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObsazeni() {
        return obsazeni;
    }

    /**
     * Sets the value of the obsazeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObsazeni(BigInteger value) {
        this.obsazeni = value;
    }

    /**
     * Gets the value of the typAkce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypAkce() {
        return typAkce;
    }

    /**
     * Sets the value of the typAkce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypAkce(String value) {
        this.typAkce = value;
    }

    /**
     * Gets the value of the typAkceZkr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypAkceZkr() {
        return typAkceZkr;
    }

    /**
     * Sets the value of the typAkceZkr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypAkceZkr(String value) {
        this.typAkceZkr = value;
    }

    /**
     * Gets the value of the semestr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemestr() {
        return semestr;
    }

    /**
     * Sets the value of the semestr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemestr(String value) {
        this.semestr = value;
    }

    /**
     * Gets the value of the platnost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatnost() {
        return platnost;
    }

    /**
     * Sets the value of the platnost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatnost(String value) {
        this.platnost = value;
    }

    /**
     * Gets the value of the den property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDen() {
        return den;
    }

    /**
     * Sets the value of the den property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDen(String value) {
        this.den = value;
    }

    /**
     * Gets the value of the denZkr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenZkr() {
        return denZkr;
    }

    /**
     * Sets the value of the denZkr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenZkr(String value) {
        this.denZkr = value;
    }

    /**
     * Gets the value of the hodinaOd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHodinaOd() {
        return hodinaOd;
    }

    /**
     * Sets the value of the hodinaOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHodinaOd(BigInteger value) {
        this.hodinaOd = value;
    }

    /**
     * Gets the value of the hodinaDo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHodinaDo() {
        return hodinaDo;
    }

    /**
     * Sets the value of the hodinaDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHodinaDo(BigInteger value) {
        this.hodinaDo = value;
    }

    /**
     * Gets the value of the hodinaSkutOd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHodinaSkutOd() {
        return hodinaSkutOd;
    }

    /**
     * Sets the value of the hodinaSkutOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHodinaSkutOd(String value) {
        this.hodinaSkutOd = value;
    }

    /**
     * Gets the value of the hodinaSkutDo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHodinaSkutDo() {
        return hodinaSkutDo;
    }

    /**
     * Sets the value of the hodinaSkutDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHodinaSkutDo(String value) {
        this.hodinaSkutDo = value;
    }

    /**
     * Gets the value of the tydenOd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTydenOd() {
        return tydenOd;
    }

    /**
     * Sets the value of the tydenOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTydenOd(BigInteger value) {
        this.tydenOd = value;
    }

    /**
     * Gets the value of the tydenDo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTydenDo() {
        return tydenDo;
    }

    /**
     * Sets the value of the tydenDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTydenDo(BigInteger value) {
        this.tydenDo = value;
    }

    /**
     * Gets the value of the tyden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTyden() {
        return tyden;
    }

    /**
     * Sets the value of the tyden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTyden(String value) {
        this.tyden = value;
    }

    /**
     * Gets the value of the tydenZkr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTydenZkr() {
        return tydenZkr;
    }

    /**
     * Sets the value of the tydenZkr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTydenZkr(String value) {
        this.tydenZkr = value;
    }

    /**
     * Gets the value of the casovaRada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCasovaRada() {
        return casovaRada;
    }

    /**
     * Sets the value of the casovaRada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCasovaRada(String value) {
        this.casovaRada = value;
    }

    /**
     * Gets the value of the kontakt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKontakt() {
        return kontakt;
    }

    /**
     * Sets the value of the kontakt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKontakt(String value) {
        this.kontakt = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the datumOd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumOd() {
        return datumOd;
    }

    /**
     * Sets the value of the datumOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumOd(String value) {
        this.datumOd = value;
    }

    /**
     * Gets the value of the datumDo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumDo() {
        return datumDo;
    }

    /**
     * Sets the value of the datumDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumDo(String value) {
        this.datumDo = value;
    }

    /**
     * Gets the value of the druhAkce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDruhAkce() {
        return druhAkce;
    }

    /**
     * Sets the value of the druhAkce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDruhAkce(String value) {
        this.druhAkce = value;
    }

    /**
     * Gets the value of the vsichniUciteleUcitIdno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVsichniUciteleUcitIdno() {
        return vsichniUciteleUcitIdno;
    }

    /**
     * Sets the value of the vsichniUciteleUcitIdno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVsichniUciteleUcitIdno(String value) {
        this.vsichniUciteleUcitIdno = value;
    }

    /**
     * Gets the value of the vsichniUciteleJmenaTituly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVsichniUciteleJmenaTituly() {
        return vsichniUciteleJmenaTituly;
    }

    /**
     * Sets the value of the vsichniUciteleJmenaTituly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVsichniUciteleJmenaTituly(String value) {
        this.vsichniUciteleJmenaTituly = value;
    }

    /**
     * Gets the value of the vsichniUcitelePrijmeni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVsichniUcitelePrijmeni() {
        return vsichniUcitelePrijmeni;
    }

    /**
     * Sets the value of the vsichniUcitelePrijmeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVsichniUcitelePrijmeni(String value) {
        this.vsichniUcitelePrijmeni = value;
    }

    /**
     * Gets the value of the referencedIdno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReferencedIdno() {
        return referencedIdno;
    }

    /**
     * Sets the value of the referencedIdno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReferencedIdno(BigInteger value) {
        this.referencedIdno = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

}
