version: '3'

services:
 mysqldb:
  image:    mysql
  container_name: database_host
  restart:  always
  environment:
   - MYSQL_DATABASE=where2study
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=user
   - MYSQL_PASSWORD=toor
  ports:
   - "8989:3306"
  volumes:
   - ./data/db/mysql:/var/lib/mysql/:z
